---
apiVersion: v1
kind: Service
metadata:
  name: aqt-app
  labels:
    app: aqt-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: aqt-app
  type: LoadBalancer
...
